name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/indian-address:v1

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Pull and restart container
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/indian-address:v1
          
          docker stop indian-adress || true
          docker rm indian-adress || true

          # Tag the image locally so the exact command can be run
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/indian-address:v1 indian_address:v1

          # Your exact command
          docker run -d --name indian-adress --restart unless-stopped --network custom_bridge --ip 172.25.0.12 -p 8282:8282 indian_address:v1
